# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewUser = channel.unary_unary(
                '/proto.BookingService/NewUser',
                request_serializer=booking__pb2.NewUserRequest.SerializeToString,
                response_deserializer=booking__pb2.NewUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/proto.BookingService/GetUser',
                request_serializer=booking__pb2.GetUserRequest.SerializeToString,
                response_deserializer=booking__pb2.GetUserResponse.FromString,
                )
        self.NewRoom = channel.unary_unary(
                '/proto.BookingService/NewRoom',
                request_serializer=booking__pb2.NewRoomRequest.SerializeToString,
                response_deserializer=booking__pb2.NewRoomResponse.FromString,
                )
        self.GetRoom = channel.unary_unary(
                '/proto.BookingService/GetRoom',
                request_serializer=booking__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=booking__pb2.GetRoomResponse.FromString,
                )
        self.NewBooking = channel.unary_unary(
                '/proto.BookingService/NewBooking',
                request_serializer=booking__pb2.NewBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.NewBookingResponse.FromString,
                )
        self.GetBooking = channel.unary_unary(
                '/proto.BookingService/GetBooking',
                request_serializer=booking__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.GetBookingResponse.FromString,
                )


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.NewUser,
                    request_deserializer=booking__pb2.NewUserRequest.FromString,
                    response_serializer=booking__pb2.NewUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=booking__pb2.GetUserRequest.FromString,
                    response_serializer=booking__pb2.GetUserResponse.SerializeToString,
            ),
            'NewRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.NewRoom,
                    request_deserializer=booking__pb2.NewRoomRequest.FromString,
                    response_serializer=booking__pb2.NewRoomResponse.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=booking__pb2.GetRoomRequest.FromString,
                    response_serializer=booking__pb2.GetRoomResponse.SerializeToString,
            ),
            'NewBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.NewBooking,
                    request_deserializer=booking__pb2.NewBookingRequest.FromString,
                    response_serializer=booking__pb2.NewBookingResponse.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=booking__pb2.GetBookingRequest.FromString,
                    response_serializer=booking__pb2.GetBookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/NewUser',
            booking__pb2.NewUserRequest.SerializeToString,
            booking__pb2.NewUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/GetUser',
            booking__pb2.GetUserRequest.SerializeToString,
            booking__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/NewRoom',
            booking__pb2.NewRoomRequest.SerializeToString,
            booking__pb2.NewRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/GetRoom',
            booking__pb2.GetRoomRequest.SerializeToString,
            booking__pb2.GetRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/NewBooking',
            booking__pb2.NewBookingRequest.SerializeToString,
            booking__pb2.NewBookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.BookingService/GetBooking',
            booking__pb2.GetBookingRequest.SerializeToString,
            booking__pb2.GetBookingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
